[pytest]

addopts = -v --html=reports/report.html --self-contained-html

testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: Smoke tests
    regression: Regression tests
    api: API test cases
    schema: Schema validation tests
    performance: Performance related tests